### ISSUE TITLE
Browserify throws errors when using Literate CoffeeScript (".litcoffee")

### ISSUE THREAD

**Issue by deltaidea** [benbria/browserify-coffee-coverage#2]
Looks like this package doesn't support Literate CoffeeScript: [`index.js#L62`](https://github.com/benbria/browserify-coffee-coverage/blob/14ce2a6f618c17d9e6ec315a8181b92c21228b71/index.js#L62).
Would you accept a PR that adds this feature?

**Comment by calvinwiebe** [comment]
I certainly would. :)

**Comment by deltaidea** [comment]
Done. :)

**Comment by calvinwiebe** [comment]
Implemented in `v1.1.0`
